title: La mobilité en commun(s)
email: comobi@beta.gouv.fr
logo: images/logo-comobi-sfb

territoires:
  - nom: "Station de ski Valberg"
    adresse: "http://azur.comobi.fr"
  - nom: "Association OTEMA SMA"
    adresse: "http://tarn.comobi.fr"

sass:
  sass_dir: _sass
  style: compressed



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile']
